# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  print_hey:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hey"
          command: "echo Hey, World!"

  print_world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "How far world"
          command: "echo , World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print_hey:
          requires:
           - say-hello
      - print_world
    