# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# My name is Daniel
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_hey:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $Main_VAR # this env var must be set within the project
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt


  print_world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "How far world"
          command: "echo , World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print_hey
      - print_world
    
